### ISSUE TITLE
Make a new PR for updates to contributions

### ISSUE THREAD

**Issue by deadline007** [Rishikesh-12/HacktoberFest2020#145]
@ankitamandal07 @An-prog-hub @girdhar18 can you all make one more pull request, I need to add your names for contributions.

**Comment by akrish4** [comment]
> @ankitamandal07 @An-prog-hub @girdhar18 can you all make one more pull request, I need to add your names for contributions.

@deadline007  they never merge it , they ask to make new PR instead of merging the older ones , they just closes the older PR and ask to open a new PR , they just merge their frnds pr thats all and i think they don't even know the meaning of open source contribution , contribution ican be anaything from  small to  big , it actualy doesn't matter how great is you contribution , it ony matters that u are having a interest to make a PR , @deadline007  dont waste ur time in requesting them to accept it. i myself have made 3 PR as of now after the owner of this repo asked me to do , he could have merged it , i have included 1 java and python basic programs but he never merges it , he just want to increse the no of PR on his repo , just a selfish behaviour from the owner of this repo.

**Comment by deadline007** [comment]
Hello, @akrish4 I am one of the reviewer and collabrotor of this repository.
There are many pull request pending to merge, we need to review them before merging. However in your case, I remember that you made your first pr on 30th of september that why it was closed. I think the second pr was closed by you only.

Although, I think @Rishikesh-12 commented that your pr were in conflit with the master branch and requested you to update new pr. Which was never followed by you..

**Comment by deadline007** [comment]
@akrish4  Kindly mention all your pull request number which youmade on this repository.
I will again review them for you.

**Comment by deadline007** [comment]
> @ankitamandal07 @An-prog-hub @girdhar18 can you all make one more pull request, I need to add your names for contributions.

These guys made great contribution to the project and thus their pr was merged and you can find their name on the wall of contributions.

**Comment by akrish4** [comment]
hello @deadline007  , When i forked this repo , it had just 10 forks and i was the first person to open a PR and was having just 2 basic programs which will never have a conflicts and then he was giving very unprofessional excuses like he needs more time to review and it was just 2 small programs basic one and he can't even review two small programs it will maximum take 10minutes then after my PR , 4 more PR were accepted by him , he had time to review those 4 but not mine , such a selfish and I don't know what is wrong with him i think he might have merged his frnds pr without even reviewing , even after 2 days he couldn't merge it and he don't even know the meaning of open source contribution , just a interest to contribute is what matters more than a great contribution. @Rishikesh-12 thank you for showing such a unprofessional behaviour and good luck for your future. and @deadline007  thank you for replying back. I don''t want to make any new PR with this repo as it is of time waste for me because he never merges it instead i will contribute to any other repo , not all owners are a selfish and unprofessional like him.

**Comment by deadline007** [comment]
#64

**Comment by deadline007** [comment]
![image](https://user-images.githubusercontent.com/66679154/94998973-8c98e200-05d3-11eb-830d-8a6042d3803c.png)

**Comment by Rishikesh-12** [comment]
Thank you @deadline007 for handling this issue.

**Comment by Rishikesh-12** [comment]
Thank you @akrish4 for opening pull requests, If there is a conflict issue with the branch, its not my fault.
Thank you for your concerns regarding my future. 
If on any day you would like to make a pr at this repository, we will be glad to merge it after it **passes the review**.
